### ISSUE TITLE
DIR /O support

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#11]
to be implemented

**Comment by bttrx** [comment]
Sorry, but I have to reopen this issue, because DIR (even without /O param) is broken for me now!

DIR doesn't find any files, but shows "Directory of Volume Serial Number is [...]" instead.
Tested on default SvarDOS, but also on MS-DOS 6.22.

Additionally, param format "/o:d" (with a colon) is not accepted, although it is advertised on the help screen.

![grafik](https://github.com/SvarDOS/bugz/assets/15858666/77dbb9a0-61e0-4015-9593-ee22b8518465)

**Comment by mateuszviste** [comment]
thanks for the quick test! It's strange as it does work for me, but I tested it only on DOSemu so far, so maybe there's some emulation glitch. I'm still working on DIR anyway, so your feedback's timing is excellent.

You are also right about the "O:xxx" format - I've never implemented it, and actually forgot that MSDOS did support such thing.

I will finish the things I'm currently on and then I will look on these two issues.

**Comment by mateuszviste** [comment]
BTW: when you test trunk software (much appreciated!), please make sure you do an explicit "wmake clean" before (re)compiling it, otherwise the linker might link to stale symbols sometimes which could lead to a large spectrum of odd behaviors. I'm not saying this is the issue, it's a general "just in case".

**Comment by mateuszviste** [comment]
> DIR doesn't find any files, but shows "Directory of Volume Serial Number is [...]" instead. Tested on default SvarDOS, but also on MS-DOS 6.22.

Fixed now. The routine that fetches the volume's serial number was overwriting a memory buffer used by DIR.
It worked for me because DOSemu does not report any serial number for its emulated volumes.

**Comment by bttrx** [comment]
I confirm the "Directory of Volume Serial Number is [...]" fix for VirtualBox. :-)

But I found a problem with `DIR /O:N`: Sort order of names depends on the language, but SvarCOM DIR doesn't take this into account currently. Just comparing ASCII values isn't enough for sorting properly. ;-)

Example:

1. `md a`
2. `md b`
3. `md ä`
4. `dir /o:n` on MS-DOS 5.0 with `COUNTRY=049,850,C:\DOS\COUNTRY.SYS` shows dirs in this order: `A` -> `Ä` -> `B`
5. `dir /o:n` on MS-DOS 5.0 with same settings + 'trunk' SvarCOM shows dirs in this order: `A` -> `B` -> `Ä`

I think, [Int 21/AX=6506h](https://www.ctyme.com/intr/rb-3163.htm "Int 21/AH=65h") is your friend here, although I never used this function myself.

**Comment by mateuszviste** [comment]
that is true, yes - and I am aware of this limitation. I was half-key hoping nobody would notice. :)
I do not know if I will work on this before 2024.2, so I've put this into a separate issue.
This is not the only thing that might be bad wrt NLS support. For example: I have implemented proper NLS in the LCASE-ing routine (used with /b), but not in the UPCASE-ing routine. NLS support in general would require some more testing for sure.
BTW is the EDR-DOS kernel having NLS support at all?

**Comment by bttrx** [comment]
> BTW is the EDR-DOS kernel having NLS support at all?

Glancing at the source code: Yes.

@boeckmann or @ecm-pushbx probably know more details how mature this is.

**Comment by ecm-pushbx** [comment]
I don't know much about any DOS's NLS things and this extends to EDR-DOS too.

**Comment by bttrx** [comment]
> I don't know much about any DOS's NLS things and this extends to EDR-DOS too.

Now it's time to extend your knowledge. ;-)

**Comment by boeckmann** [comment]
> BTW is the EDR-DOS kernel having NLS support at all?

DISCLAIMER: I'm still affected by some brain fog caused by a virus infection, so take the following with a grain of salt:

Yes, the EDR kernel actually it has quite extensive NLS support, even without NLSFUNC being loaded. The kernel installs an interim INT 2F,14XX handler [1] provided by itself (normally provided by NLSFUNC) for loading country information from COUNTRY.SYS while processing CONFIG.SYS. After that, INT2F,14XX support is gone, but INT21,65XX etc. are fully supported without relying on NLSFUNC. There is an option to make the kernel smaller by giving a NLSFUNC definition to the assembler. Then country load functions are stripped from DRDOS.SYS, and the kernel relies on external NLSFUNC routines for loading country data after boot [2].

The format of the COUNTRY.SYS file is different to the one e.g. provided by FreeDOS. This is the reason why my latest EDRDOS package contains a EDR specific COUNTRY.SYS.

[1] https://github.com/SvarDOS/edrdos/blob/9751c114b84df883956fa289a0142dfe54b57854/drbio/nlsfunc.a86#L111
[2] https://github.com/SvarDOS/edrdos/blob/9751c114b84df883956fa289a0142dfe54b57854/drdos/misc.a86#L1511

**Comment by boeckmann** [comment]
> There is an option to make the kernel smaller by giving a NLSFUNC definition to the assembler

Update: NLSFUNC actually IS defined: https://github.com/SvarDOS/edrdos/blob/9751c114b84df883956fa289a0142dfe54b57854/drdos/misc.a86#L67

P.S.: I do not like configuration definitions scattered around code :-)
