### ISSUE TITLE
Support existing DOS installations?

### ISSUE THREAD

**Issue by evan** [SvarDOS/bugz#37]
I totally understand if you don't want to do this.

I am using the SvarDOS pkg system with DOS622. I switched to DOS622 partly because the FreeDOS utilities (more, edit) were too slow, which I see you are fixing independently. However, others probably have different reasons for not wanting to use FreeDOS, and it would lower the commitment required to give SvarDOS a try. 

I installed it by setting up SvarDOS first and then replacing the DOS installation with MS-DOS and copying some things over like the locale files. I was surprised that this worked so well.

It would be great if SvarDOS could detect an existing DOS installation and give you the option to install the pkg manager and its dependencies alongside it, instead of starting from scratch. My understanding is MS-DOS >5 and similar is compatible. 

Failing this, at least there could be some instructions for how to do this manually somewhere prominent.

**Comment by mateuszviste** [comment]
If I understand correctly you basically use pkg + pkgnet on MSDOS, like an "application market" of sorts. I have nothing against people dismembering SvarDOS to use whatever works for them, but I am not really keen on promoting such practice - if only to avoid the moral liability should the user's system become broken in the process due to some completely untested configuration/environment.

**Comment by evan** [comment]
Yeah, I use it as a standalone package manager like Homebrew or Chocolatey. 

That's fine; once I get everything working maybe I will try to switch to full SvarDOS. In true Microsoft style I am uneasy enough about FreeDOS that I don't want to be wondering if it's the reason some driver, card or program isn't working right now.

**Comment by mateuszviste** [comment]
Slight update: since 20240225 the build system generates a little ZIP archive that contains the basic components for SvarDOS-style package management, along with some (very sparse) instructions. This package is meant to become a public redistribuable so people using other DOSes can also use the SvarDOS repo.

The file is named "svarstub.zip" and can currently be downloaded here:
http://svardos.org/?p=files&dir=20240225

The included README is in desperate need of love, but this will be an improvement for another time. Once it cleaner, I will publish a link to this somewhere on the main page of the website.

**Comment by evan** [comment]
Great, ok. I need to redo my XT install, when I do I will use this.
