### ISSUE TITLE
SvarCOM: CD fails if destination dir contains trailing slash

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#40]
This fails with "path not found": `cd somedir\`, while `cd somedir` works.

Expected behaviour: `cd somedir\` changes the working directory to `somedir`.

**Comment by mateuszviste** [comment]
the "path not found" is what the FreeDOS kernel answers. SvarCOM just calls INT 21h,AH=3Bh ("CHDIR") and passes the argument as-is.
Should SvarCOM sanitize the argument before passing it to the kernel? I'm not convinced about this, since current behavior is consistent with MS-DOS (and MS COMMAND.COM).

![image](https://github.com/SvarDOS/bugz/assets/9503501/90a79f1b-1c05-4517-aa32-1f970aad21e0)

**Comment by mateuszviste** [comment]
same on MS-DOS 6.00

![image](https://github.com/SvarDOS/bugz/assets/9503501/d7b94e2d-271c-45ce-9658-6d4baaa984b4)

**Comment by mateuszviste** [comment]
same on EDR-DOS 7.01

![image](https://github.com/SvarDOS/bugz/assets/9503501/9f733f6e-c5c2-4f83-8e4a-c4b35c59468a)

**Comment by boeckmann** [comment]
Yes you are right. I am currently dealing with too many shells. 4dos accepts the trailing slash, but MS command.com does not. Sorry!

**Comment by mateuszviste** [comment]
breaking news: the trailing blackslash is tolerated in MS-DOS 6.22.
but then, it also works under SvarCOM when running under the MS-DOS 6.22 kernel... meaning it's kernel-dependent anyway, not a COMMAND.COM feature.

![image](https://github.com/SvarDOS/bugz/assets/9503501/c1368098-9d43-4344-8a9c-7fde31dc213c)

**Comment by boeckmann** [comment]
> breaking news: the trailing backslash is tolerated in MS-DOS 6.22. but then, it also works under SvarCOM when running under the MS-DOS 6.22 kernel... meaning it's kernel-dependent anyway, not a COMMAND.COM feature.

Nice! Than your 6.22 works better than mine :-D
![IMG_0056](https://github.com/SvarDOS/bugz/assets/6333969/76b9af8c-7460-482e-8cf3-e99a6e09f0a0)

**Comment by mateuszviste** [comment]
I've found the reason. I have tested MS-DOS 5.0, MS-DOS 6.0 and EDR-DOS on VirtualBox, but the 6.22 test was done under DOSEmu (because I just had a convenient 6.22 install there) - and that's the error. DOSEmu performs some I/O black magic under the hood, so the "CD to dir with a trailing backslash" support actually came from DOSEmu.
