### ISSUE TITLE
Latin American installation/keyboard not supported from INSTALL

### ISSUE THREAD

**Issue by igully** [SvarDOS/bugz#46]
Latin American installation/keyboard not supported from INSTALL. 

Latin America includes all the following countries: Argentina, Bolivia, Brazil, Chile, Colombia, Costa Rica, Cuba, Ecuador, El Salvador, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay and Venezuela.

Working and valid Latin American keyboard setting available by entering: 
KEYB LA

**Comment by mateuszviste** [comment]
Hi igull, is the same codepage used for all these countries? Can you please tell what codepage that is?

Currently the SvarDOS installer supports already the Brazilian keyboard layout and it appears to be either "KEYB BR" or "KEYB BR274" depending on the layout, but not "KEYB LA". Can you explain the difference?

**Comment by mateuszviste** [comment]
okay, found out this document: http://home.mnet-online.de/willybilly/fdhelp-internet/en/hhstndrd/base/kpdos.htm
"keyb la" seems indeed common to a few latin-american countries, but not brazil. it also seems compatible with CP437 which makes things easier for the installer.

**Comment by mateuszviste** [comment]
@igully here's a test run: http://svardos.org/?p=files&dir=20240115 could you please check it out to confirm it behaves as you'd expect?

**Comment by igully** [comment]
> Hi igull, is the same codepage used for all these countries? Can you please tell what codepage that is?
> 
> Currently the SvarDOS installer supports already the Brazilian keyboard layout and it appears to be either "KEYB BR" or "KEYB BR274" depending on the layout, but not "KEYB LA". Can you explain the difference?

Hi, Brazilians have their own language which is a slight local modification of Portuguese which is totally different from what Latin American countries use. These Latin American countries all use a local derivative of Spanish.

**Comment by igully** [comment]
It is just problematic, because when in common slang you refer to Latin America you must include Brazil, despite having a totally different language.

**Comment by igully** [comment]
> @igully here's a test run: http://svardos.org/?p=files&dir=20240115 could you please check it out to confirm it behaves as you'd expect?

No, unfortunately not:

The Welcome screen should allow me to choose "Spanish" as my preferred language. and then set KEYB LA codepage 437.

**Comment by igully** [comment]
If I choose "English" as my preferred language and then the Latin American keyboard, at least I will get the matching LA keyboard that works properly.

But, again, the initial place Latin Americans will go to look for their regional settings is by choosing the "Spanish" language.

To make it more clear, the Latin American language is as related to Spanish, as American English is related to British English.

**Comment by mateuszviste** [comment]
> If I choose "English" as my preferred language and then the Latin American keyboard, at least I will get the matching LA keyboard that works properly.

Cool, so it works as expected. Thanks for checking it out.

> But, again, the initial place Latin Americans will go to look for their regional settings is by choosing the "Spanish" language.

I understand, but that's an entirely different task. This issue was about latin-american keyboard handling, which is easy to add through a minor change of the SvarDOS installer. What you mention now is full blown Spanish support, which is implies lots of translation works.

My Spanish level is limited to about 5 words, like "loco hermano" and a couple of other that I'd rather not repeat publicly. Point being I am unable to translate what is needed. Would you be willing to provide ES versions of the SvarDOS files?

A good start would be translating these two files:
http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Finstall%2Ftrunk%2Fnls%2Fen_utf8.txt
http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Flang%2Fen-utf8.txt

If you'd be willing to put in such translation work, please create a separate bug issue so we can track it easier. In any case, I will be glad to add Spanish to SvarDOS.

**Comment by igully** [comment]
Thank you again Mateusz.

I will translate those two files you mentioned and create a bug report for them.
