### ISSUE TITLE
DOSKEY package should be integrated in the default INSTALL

### ISSUE THREAD

**Issue by igully** [SvarDOS/bugz#48]
On one hand, there is nothing more annoying than having to retype a command due to a typo, especially on long lines. 

On the other hand, one of the first issues I encountered when using SvarDOS, which I am sure most others will find too, is that EDIT was missing when attempting to edit something. After a minute or so, I found SVED was its sort of functional replacement. An alias would have helped to quickly move on from this issue.

By including the DOSKEY 2.8 you can easily resolve the above two issues any newcomer as me might find.

**Comment by boeckmann** [comment]
I think it is a good idea to alias SVED to EDIT. People can not be expected to know the name of the editor when trying SvarDOS.

**Comment by mateuszviste** [comment]
Yes, I had thought about it when including sved into SvarDOS, but ultimately I refrained from adding an alias (or even renaming sved.com to edit.com) because I wanted to allow having both sved and a "normal" edit possible for people that prefer to stick with FreeDOS edit. It is true however that the current status is not very intuitive to newcomers.

I see four options:

1. document this in some post-install script, so after boot there would be a short, half-screen intro into SvarDOS basics: what the system editor is, some words about the integrated HELP, a mention of DOSKEY and why it could be a good idea to install it and possibly one or two other oddities.
2. rename sved.com to edit.com
3. add an EDIT.BAT file to %PATH% that would call SVED.COM %1 %2 %3...
4. add an EDIT.BAT file to %PATH% that would say "there is no EDIT on this system, use SVED instead"

My personal preference would be either 1 or 4. The last one is esp. appealing because *.BAT file are called only after COM and EXE, so it would be executed only in the event that there really is no EDIT.COM/EDIT.EXE available.

Any extra thoughts?

About DOSKEY: while I do use it myself, I am not very keen on adding it to the default install. I like to think of SvarDOS as a truly bare bone system/skeleton that fits on a single floppy, and then everything else is add-ons that user has to tailor suiting his needs. Some users will want DOSKEY, others won't because they might want to save every byte of memory, and others might prefer using 4DOS or FreeCOM, both of which have a DOSKEY-like feature embedded.

**Comment by boeckmann** [comment]
4. seems fine to me 👍

**Comment by igully** [comment]
> 4. seems fine to me 👍

I have to agree too. If adding DOSKEY is not an option, that seems to be the best solution.

**Comment by bttrx** [comment]
I also vote for option 4.

**Comment by mateuszviste** [comment]
option 4 it is then. :)
I have updated the sved package so it includes an informational EDIT.BAT file.

**Comment by bttrx** [comment]
@mateuszviste

Version 2023.5+1 doesn't show up here, when I run `pkgnet search sved`.

**Comment by mateuszviste** [comment]
> Version 2023.5+1 doesn't show up here, when I run `pkgnet search sved`.

Totally my fault - I cloned the package, edited it by adding the BAT file, changed the package's filename, but forgot to update the version string in the LSM file... Oops.

Fixed right now.
