### ISSUE TITLE
pkg update should add an implicit SVP extension if missing

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#70]
"pkg install" adds a "svp" extension to files when no extension is provided, so this works:

````
pkg pull edrdos
pkg install edrdos
````

but "pkg update" does not have this intelligence:

````
pkg pull edrdos
pkg update edrdos
ERROR: Invalid zip archive!
````

**Comment by bttrx** [comment]
`pkg pull edrdos` is wrong syntax, because `pull` is supported by `pkgnet` only.

I had no problems when updating DOSMID ver 0.9.6 to 0.9.7 by running `pkg update dosmid`.

I'm running PKG ver 20240131.

You may want to look at http://svn.svardos.org/comp.php?repname=SvarDOS&compare[]=%2Fpkg%2Ftrunk%2Fpkginst.c@1599&compare[]=%2Fpkg%2Ftrunk%2Fpkginst.c@1600

**Comment by mateuszviste** [comment]
You are right, it seems Mateusz already fixed that without me noticing. I guess I was running an old pkg binary when I noticed this issue. Should have verified that I'm running the latest version of the software before reporting bugz!

Thanks for your control check, and sorry for the noise.

(and yes of course I meant to write "pkgnet pull"... I encountered this issue on my 386 last week - real hardware is nice but it is missing a "screenshot-to-clipboard" feature!)

**Comment by bttrx** [comment]
> but it is missing a "screenshot-to-clipboard" feature!

I'm sure, you would find a solution yourself, but for the others: Dos Navigator (even 1999 version 1.51) comes with a built-in screen grabber. You can start it from the hamburger menu or via Shift+Alt+Ins. Also there is the Snipper package in the repo.
